safe: false
port: 4000
name: BastenGao's Blog
sub_title: " - Web, Rails, Ruby, Java"
author: bastengao
description: bastengao 的博客，主要专注于技术开发、Web、Ruby、Rails、Java 等。
keywords: bastengao,博客,个人博客,技术博客
url: http://bastengao.com
# url: http://localhost:4000

source:      .
destination: ./_site
plugins:     ./_plugins
exclude:     ["CNAME", "README.md"]
timezone:    China/BeiJing
sitemap: true

future:      true
lsi:         false
highlighter: pygments
markdown:    redcarpet
permalink:   /blog/:categories/:year/:month/:title.html

kramdown:
  input: GFM
  use_coderay: true

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcarpet:
  extensions: ["fenced_code_blocks"]

gems:
  - jekyll-sitemap
  - jekyll-feed
