safe:        false
auto:        false
server:      false
server_port: 4000
url: http://localhost:4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    rdiscount
permalink:   date

rdiscount:
  extensions: []
