safe:        false
auto:        false
server:      false
server_port: 4000
name: BastenGao's Blog
description: BastenGao's Blog
url: http://bastengao.com

source:      .
destination: ./_site
plugins:     ./_plugins
exclude:     ["CNAME"]

future:      true
lsi:         false
pygments:    false
markdown:    rdiscount
permalink:   /blog/:categories/:year/:month/:title.html

rdiscount:
  extensions: []
