safe: false
port: 4000
name: BastenGao's Blog
sub_title: " - Web, Rails, Ruby, Java"
author: bastengao
description: bastengao 的博客，主要专注于技术开发、Web、Ruby、Rails、Java 等。
keywords: bastengao,博客,个人博客,技术博客
url: https://bastengao.com
# url: http://localhost:4000

exclude:     ["CNAME", "README.md", "tag_generator.py"]
timezone:    China/BeiJing
sitemap: true

future:      true
permalink:   /blog/:categories/:year/:month/:title.html

highlighter: null

kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-sitemap
  - jekyll-feed
