safe:        false
port: 4000
name: BastenGao's Blog
description: BastenGao's Blog
url: http://bastengao.com

source:      .
destination: ./_site
plugins:     ./_plugins
exclude:     ["CNAME"]

future:      true
lsi:         false
pygments:    true
markdown:    redcarpet
permalink:   /blog/:categories/:year/:month/:title.html

redcarpet:
  extensions: ["fenced_code_blocks"]
