safe: false
port: 4000
name: Basten Gao's Blog
author: bastengao
description: Basten Gao's Blog
url: http://bastengao.com

source:      .
destination: ./_site
plugins:     ./_plugins
exclude:     ["CNAME", "README.md"]
timezone:    China/BeiJing
sitemap: true

future:      true
lsi:         false
highlighter: pygments
markdown:    redcarpet
permalink:   /blog/:categories/:year/:month/:title.html

kramdown:
  input: GFM
  use_coderay: true

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcarpet:
  extensions: ["fenced_code_blocks"]

gems:
  - jekyll-sitemap
