safe:        false
auto:        false
server:      false
server_port: 4000
url: http://bastengao.com

source:      .
destination: ./_site
plugins:     ./_plugins
exclude:     ["CNAME"]

future:      true
lsi:         false
pygments:    false
markdown:    rdiscount
permalink:   date

rdiscount:
  extensions: []
